blank_issues_enabled: false
contact_links:
  - name: Any other suggestions, ideas, queries, any topic of discussions?
    url: https://github.com/WasiqB/coteafs-datasource/discussions
    about: Start discussion here.